{% set version = "1.22-6" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-gam
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/gam_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/gam/gam_{{ version }}.tar.gz
  sha256: 249afaa3497ba1279ff5d7f61e0e46c56becff72db42cdb464867563937351d5

build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - cross-r-base {{ r_base }}        # [build_platform != target_platform]
    - r-foreach                        # [build_platform != target_platform]
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ compiler('fortran') }}        # [not win]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - {{ posix }}filesystem            # [win]
    - {{ posix }}make
    - {{ posix }}sed                   # [win]
    - {{ posix }}coreutils             # [win]
    - {{ posix }}zip                   # [win]
  host:
    - r-base
    - r-foreach
  run:
    - r-base
    - r-foreach

test:
  commands:
    - $R -e "library('gam')"           # [not win]
    - "\"%R%\" -e \"library('gam')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=gam
  license: GPL-2.0-only
  summary: Functions for fitting and working with generalized additive models, as described in chapter 7 of "Statistical Models in S" (Chambers and Hastie (eds), 1991), and "Generalized Additive Models" (Hastie and Tibshirani, 1990).
  license_family: GPL2
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
