{% set version = "1.22-4" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-gam
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/gam_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/gam/gam_{{ version }}.tar.gz
  sha256: 78417408f5eebb6fc951665698215e3f8c5fac4e7b694a324550d5f4918ac073

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ compiler('fortran') }}        # [not win]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-foreach
  run:
    - r-base
    - r-foreach

test:
  commands:
    - $R -e "library('gam')"           # [not win]
    - "\"%R%\" -e \"library('gam')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=gam
  license: GPL-2.0-only
  summary: Functions for fitting and working with generalized additive models, as described in chapter 7 of "Statistical Models in S" (Chambers and Hastie (eds), 1991), and "Generalized Additive Models" (Hastie and Tibshirani, 1990).
  license_family: GPL2
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: gam
# Type: Package
# Title: Generalized Additive Models
# Date: 2018-07-19
# Version: 1.16.1
# Author: Trevor Hastie
# Description: Functions for fitting and working with generalized additive models, as described in chapter 7 of "Statistical Models in S" (Chambers and Hastie (eds), 1991), and "Generalized Additive Models" (Hastie and Tibshirani, 1990).
# Maintainer: Trevor Hastie <hastie@stanford.edu>
# Depends: stats, splines, foreach
# Suggests: akima
# License: GPL-2
# NeedsCompilation: yes
# Packaged: 2019-07-03 07:29:25 UTC; ripley
# Repository: CRAN
# Date/Publication: 2019-07-03 08:10:33 UTC
