{% set version = "1.16" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-gam
  version: {{ version|replace("-", "_") }}

source:
  fn: gam_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/gam_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/gam/gam_{{ version }}.tar.gz
  sha256: 020532e49e59b8691dbbdd44fdaee6c0cf7334708b3080c24706140edf238f2e

build:
  merge_build_host: True  # [win]
  number: 1
  skip: true  # [win32]

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - posix                # [win]
    - {{ compiler('fortran') }}        # [unix]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - {{ compiler('c') }}        # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
  host:
    - r-base
    - r-foreach

  run:
    - r-base
    - r-foreach

test:
  commands:
    - $R -e "library('gam')"  # [not win]
    - "\"%R%\" -e \"library('gam')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=gam
  license: GPL-2
  summary: Functions for fitting and working with generalized additive models, as described in
    chapter 7 of "Statistical Models in S" (Chambers and Hastie (eds), 1991), and "Generalized
    Additive Models" (Hastie and Tibshirani, 1990).
  license_family: GPL2

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
