appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: NMqVmHBvfh00zClI2H02DAFlKwrg1O1lhwoIhOnYWCFCAWVPP4hTsqybSX2UvvYoGAqkG9ZKeuou8XVZpgHCVOfRyOTDxKwC+TnAw8pMb4Q+irPewXU7PSHJyFOMd0Cn2AZFns3slF+498eM0iUoDd6S9Y5LORY8mI7tM8+YIIbpH1YpaQ6KoNJjhClC2LLBeXiu0XOyxEOmZ0rIOXleBdvUYhGtsvKkhm16sIyFLl2HiXxliaEfp3WVQpxZBP8hXeNG43nXFnFoFd7q1DdeCRPpS9iiuxHp0qCC+NcgP8dsDbiDXH2SxCBlFUw8MheQENtN6vglKk3E1d+9I3Kq+87GtJqsAhAHgAIUTHKNs7RsGjZXosTKDDoRlqiCTlqxWLYL6a3RlaRpXvCoRGDADEffM0kEm1DnJZ9gla5i1bdLbj27LrPicsAe6BMiypvDhPbONPWpoucszZe5Jhk3qWH8jcPUPCZxCU9r/xR//GkMnEJ64uBXK3H0wKRcvpr7HpDyzsoPlp3TVW/uMF1IEo1RSsHjBVY0R5CJrvXgWSe66YoTyTiVtA2tA9lXBULmnOi9dKHaMasQQ5oNwp3AetlLea5nzh1cQe5lC2L+AI9eC3ogh/gaMZu8lzGVGykaOjTB2PYRsrRBVc7p5SnF3KWJJYaPnqCJ7Ppk0kXExh4=}
bot:
  automerge: true
