travis:
  secure:
    BINSTAR_TOKEN: N8CTRbd6QKGSpMoEU86quZYs0zigDuFQF5jZReKVHIzEmVvI4lYdvjbAz/y+XA382CAd+S0cOkf0M/xqOAfv3n2FGdaBapEAEd3690wRkz9hFqok0+lXqi83Kl+oCakE4njqYI/9ijOT4TuPOQCgXHZBcYJRjAQfgIrk4PsHOsq6WeEJm63TXaqCp/TC2UDnJ0Wb6FRk8AhVqaJlf1BbNc3HGRAk2fCwDz5gyvymP0+YGjE/Kx+iKJeI2klZdTJHhdo2fNB2fEtXawUFcTQLG+CCudtV7E9/V6mOQ5BY6+KcMzhak8WcoF7CaqLFIoSMLnhMHqljYD2qSfdJzj+rf9p4+7uhLkgEONHeAO36gu9oVNkc/gaU+NDs9MYj8V5Q59l354O3SpCQ5YrGUW0SKQMa2Mz1vVXIfV6tVX3g3T0rBX0IDCBCQkE3TR6ahc5O/DtOJTxjOjhJraUl/ghjYoFFGSnrEEXvMExkgss8mLy6dm3ZaytZaWxaVhMdGr4T1IN9Hh2Mno5+HB4GeC7zFdbCvk3OmOe8UtA7D7rW1rcJDdPesFi/yAC9tai+pCU8Gdjo6tsZsRifBYlEXyQ96aXFRlFh/20AwzpM39iURYEbHHIkXAun3IOHj4sha6/0QO4al3LTmUfKREABExFeBITzmucn0PqVXPrgKwxHas8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
